server:
  port: 8090
  jsp-servlet: 
    init-parameters: 
      development: true #jsp auto recompile

spring:
  datasource:
    url: jdbc:mysql://10.243.141.88:3306/dc_framework_report?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://192.168.1.104:3306/dc_framework_report?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: fis
    password: fisfis
    dbcp2:
      validation-query: SELECT 1
      test-while-idle: true
  application:
    name: helloservice
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka


